# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ed79d348a0a65b7f0343255a2b7ef5fd5067b8f7b15beed535c152e33726454359c6397049020cb5add6e41d72c08619cc655ec9dc54adcf2c6044cab4e0dfd

test:
  secret_key_base: 1bc4aa19e3fca394230cb834f926365d124964d40a64ce6a841db6a24b82a18125e1796eee8b5e982cbbdee193fa17ce446393cfb0849b26dd47c37692faa62f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
